- name: Copy AAP installation file to Tower nodes
  hosts: all
  remote_user: ansible
  gather_facts: no
  tasks:
    - copy: 
        src: /Users/jruels/Downloads/ansible-automation-platform-setup-bundle-2.4-7.5-x86_64.tar.gz
        dest: /home/ansible/ansible-automation-platform-setup-bundle-2.4-7.5-x86_64.tar.gz

    - name: Extract archive on remote server
      unarchive:
        src: /home/ansible/ansible-automation-platform-setup-bundle-2.4-7.5-x86_64.tar.gz
        dest: /home/ansible
        remote_src: yes

    - name: Remove archive after extraction
      file:
        path: /home/ansible/ansible-automation-platform-setup-bundle-2.4-7.5-x86_64.tar.gz
        state: absent
